"""Dmint: Deterministic authorization and security enforcement for AI-agent tool execution."""

import sys

from .version import __version__
from .core import (
    APPROVAL_CREDENTIAL_VERSION,
    APPROVAL_RECORD_SCHEMA_VERSION,
    APPROVAL_SIGNATURE_ALGORITHM,
    CANONICALIZATION_PROFILE,
    MAX_SAFE_INTEGER,
    NO_RESOURCE,
    REQUEST_BINDING_VERSION,
    ANY_RESOURCE,
    AnyResource,
    ApprovalAlgorithmUnsupportedError,
    ApprovalAssertion,
    ApprovalAudienceInvalidError,
    ApprovalAuthority,
    ApprovalAuthorityKind,
    ApprovalConcurrentConsumeError,
    ApprovalConsumedError,
    ApprovalCredentialInvalidError,
    ApprovalDeploymentInvalidError,
    ApprovalError,
    ApprovalExpiredError,
    ApprovalIntegrationMismatchError,
    ApprovalInvalidError,
    ApprovalIssuerInvalidError,
    ApprovalMalformedError,
    ApprovalNotApprovedError,
    ApprovalNotFoundError,
    ApprovalPolicyInvalidError,
    ApprovalPrincipalMismatchError,
    ApprovalRecord,
    ApprovalRequestMismatchError,
    ApprovalRequiredError,
    ApprovalSignatureInvalidError,
    ApprovalState,
    ApprovalStoreConfigurationError,
    ApprovalStoreError,
    ApprovalVerifier,
    ApprovalVersionUnsupportedError,
    AuthorizationError,
    AuthorizedRequest,
    CanonicalizationError,
    Condition,
    ConditionOperator,
    CorruptApprovalRecordError,
    Decision,
    Dmint,
    DmintError,
    ExecutionError,
    IllegalApprovalTransitionError,
    InvocationSnapshot,
    LocalApprovalAuthority,
    MalformedApprovalError,
    NoResource,
    Policy,
    PolicyError,
    PolicyProvenance,
    RequestValidationError,
    Rule,
    ApprovalStore,
    SQLAlchemyApprovalStore,
    SQLiteApprovalStore,
    ThreadSafeApprovalStore,
    create_approval_store,
    ToolRequest,
    TrustedContext,
    UnknownApprovalStateError,
    UnknownApprovalVersionError,
    VerifiedApproval,
    WebhookConfig,
    WebhookNotifier,
    build_discord_payload,
    build_slack_payload,
    build_teams_payload,
    build_denial_payload,
    canonical_request_binding,
    canonicalize,
    canonicalize_request,
    dispatch_approval_webhook,
    dispatch_denial_webhook,
    new_approval_id,
    new_request_id,
    parse_approval_state,
    policy_digest,
    request_binding_envelope,
    request_binding_fingerprint,
    request_fingerprint,
)
import importlib
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from . import cli as cli
    from . import core as core
    from . import dashboard as dashboard
    from . import mcp as mcp
    from . import skills as skills


def __getattr__(name: str):
    if name in ("cli", "mcp", "dashboard", "skills"):
        mod = importlib.import_module(f".{name}", __name__)
        globals()[name] = mod
        sys.modules.setdefault(f"dmint_{name}", mod)
        return mod
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "__version__",
    "ANY_RESOURCE",
    "APPROVAL_CREDENTIAL_VERSION",
    "APPROVAL_RECORD_SCHEMA_VERSION",
    "APPROVAL_SIGNATURE_ALGORITHM",
    "ApprovalAlgorithmUnsupportedError",
    "ApprovalAssertion",
    "ApprovalAudienceInvalidError",
    "ApprovalAuthority",
    "ApprovalAuthorityKind",
    "ApprovalConcurrentConsumeError",
    "ApprovalConsumedError",
    "ApprovalCredentialInvalidError",
    "ApprovalDeploymentInvalidError",
    "ApprovalError",
    "ApprovalExpiredError",
    "ApprovalIntegrationMismatchError",
    "ApprovalInvalidError",
    "ApprovalIssuerInvalidError",
    "ApprovalMalformedError",
    "ApprovalNotApprovedError",
    "ApprovalNotFoundError",
    "ApprovalPolicyInvalidError",
    "ApprovalPrincipalMismatchError",
    "ApprovalRecord",
    "ApprovalRequestMismatchError",
    "ApprovalRequiredError",
    "ApprovalSignatureInvalidError",
    "ApprovalState",
    "ApprovalStoreError",
    "ApprovalVerifier",
    "ApprovalVersionUnsupportedError",
    "AuthorizationError",
    "AuthorizedRequest",
    "CANONICALIZATION_PROFILE",
    "CanonicalizationError",
    "Condition",
    "ConditionOperator",
    "CorruptApprovalRecordError",
    "Decision",
    "Dmint",
    "DmintError",
    "ExecutionError",
    "IllegalApprovalTransitionError",
    "InvocationSnapshot",
    "LocalApprovalAuthority",
    "MAX_SAFE_INTEGER",
    "MalformedApprovalError",
    "NO_RESOURCE",
    "NoResource",
    "AnyResource",
    "Policy",
    "PolicyError",
    "PolicyProvenance",
    "REQUEST_BINDING_VERSION",
    "RequestValidationError",
    "Rule",
    "ApprovalStore",
    "ApprovalStoreConfigurationError",
    "SQLAlchemyApprovalStore",
    "SQLiteApprovalStore",
    "ThreadSafeApprovalStore",
    "create_approval_store",
    "ToolRequest",
    "TrustedContext",
    "UnknownApprovalStateError",
    "UnknownApprovalVersionError",
    "VerifiedApproval",
    "canonical_request_binding",
    "canonicalize",
    "canonicalize_request",
    "new_approval_id",
    "new_request_id",
    "parse_approval_state",
    "policy_digest",
    "request_binding_envelope",
    "request_binding_fingerprint",
    "request_fingerprint",
    "WebhookConfig",
    "WebhookNotifier",
    "build_slack_payload",
    "build_discord_payload",
    "build_teams_payload",
    "build_denial_payload",
    "dispatch_approval_webhook",
    "dispatch_denial_webhook",
    "core",
    "cli",
    "mcp",
    "dashboard",
    "skills",
]
