"""Dmint's hardened Phase 1 deterministic authorization core."""

from .approvals import (
    APPROVAL_RECORD_SCHEMA_VERSION,
    CANONICALIZATION_PROFILE,
    REQUEST_BINDING_VERSION,
    ApprovalAuthority,
    ApprovalAuthorityKind,
    ApprovalRecord,
    ApprovalState,
    PolicyProvenance,
    new_approval_id,
    new_request_id,
    parse_approval_state,
)
from .authority import ApprovalAssertion, ApprovalVerifier, LocalApprovalAuthority, VerifiedApproval
from .canonicalize import MAX_SAFE_INTEGER, canonicalize, canonicalize_request
from .enforcement import AuthorizedRequest, Dmint, InvocationSnapshot
from .errors import (
    ApprovalAlgorithmUnsupportedError,
    ApprovalAudienceInvalidError,
    ApprovalConcurrentConsumeError,
    ApprovalCredentialInvalidError,
    ApprovalConsumedError,
    ApprovalDeploymentInvalidError,
    ApprovalError,
    ApprovalExpiredError,
    ApprovalIntegrationMismatchError,
    ApprovalInvalidError,
    ApprovalIssuerInvalidError,
    ApprovalMalformedError,
    ApprovalNotFoundError,
    ApprovalNotApprovedError,
    ApprovalPolicyInvalidError,
    ApprovalPrincipalMismatchError,
    ApprovalRequestMismatchError,
    ApprovalRequiredError,
    ApprovalSignatureInvalidError,
    ApprovalStoreError,
    ApprovalVersionUnsupportedError,
    AuthorizationError,
    CanonicalizationError,
    CorruptApprovalRecordError,
    DmintError,
    ExecutionError,
    IllegalApprovalTransitionError,
    MalformedApprovalError,
    PolicyError,
    RequestValidationError,
    UnknownApprovalStateError,
    UnknownApprovalVersionError,
)
from .hashing import request_fingerprint
from .models import (
    ANY_RESOURCE,
    NO_RESOURCE,
    AnyResource,
    Decision,
    NoResource,
    ToolRequest,
    TrustedContext,
)
from .policy import Condition, Policy, Rule, policy_digest
from .request_binding import (
    canonical_request_binding,
    request_binding_envelope,
    request_binding_fingerprint,
)
from .storage import SQLiteApprovalStore
from .versions import APPROVAL_CREDENTIAL_VERSION, APPROVAL_SIGNATURE_ALGORITHM

__all__ = [
    "AuthorizationError",
    "AuthorizedRequest",
    "ANY_RESOURCE",
    "APPROVAL_RECORD_SCHEMA_VERSION",
    "ApprovalAuthority",
    "ApprovalAuthorityKind",
    "APPROVAL_CREDENTIAL_VERSION",
    "ApprovalAlgorithmUnsupportedError",
    "ApprovalAudienceInvalidError",
    "ApprovalConcurrentConsumeError",
    "ApprovalCredentialInvalidError",
    "ApprovalConsumedError",
    "ApprovalDeploymentInvalidError",
    "ApprovalAssertion",
    "ApprovalError",
    "ApprovalExpiredError",
    "ApprovalIntegrationMismatchError",
    "ApprovalInvalidError",
    "ApprovalIssuerInvalidError",
    "ApprovalMalformedError",
    "ApprovalNotFoundError",
    "ApprovalNotApprovedError",
    "ApprovalPolicyInvalidError",
    "ApprovalPrincipalMismatchError",
    "ApprovalRecord",
    "ApprovalSignatureInvalidError",
    "ApprovalState",
    "ApprovalRequestMismatchError",
    "ApprovalRequiredError",
    "APPROVAL_SIGNATURE_ALGORITHM",
    "ApprovalVerifier",
    "ApprovalVersionUnsupportedError",
    "CANONICALIZATION_PROFILE",
    "CanonicalizationError",
    "Condition",
    "CorruptApprovalRecordError",
    "Decision",
    "Dmint",
    "DmintError",
    "ExecutionError",
    "IllegalApprovalTransitionError",
    "InvocationSnapshot",
    "MAX_SAFE_INTEGER",
    "MalformedApprovalError",
    "LocalApprovalAuthority",
    "NO_RESOURCE",
    "NoResource",
    "AnyResource",
    "Policy",
    "PolicyProvenance",
    "PolicyError",
    "policy_digest",
    "REQUEST_BINDING_VERSION",
    "RequestValidationError",
    "Rule",
    "SQLiteApprovalStore",
    "ApprovalStoreError",
    "ToolRequest",
    "TrustedContext",
    "UnknownApprovalStateError",
    "UnknownApprovalVersionError",
    "VerifiedApproval",
    "canonicalize",
    "canonicalize_request",
    "canonical_request_binding",
    "request_fingerprint",
    "request_binding_envelope",
    "request_binding_fingerprint",
    "new_approval_id",
    "new_request_id",
    "parse_approval_state",
]
