"""Phase 8 — dmint-mcp runtime compatibility tests.

Audit that the protection configuration generated by dmint-cli is fully
compatible with the actual dmint-mcp runtime parser and enforcement engine.

Rules:
- NO fake/mock parsers are used for dmint_mcp classes.
- Every MCPIntegrationConfig, EnforcementGate, MCPRequestMapper, and
  DmintMCPProxy is the real production class from dmint.mcp.
- Tests drive the full pipeline:
    1. Build a generated mcp_protection.json artifact (as the wizard would).
    2. Parse it exactly as validate_mcp_protection_config does.
    3. Construct the real MCPIntegrationConfig from parsed data.
    4. Wire the real EnforcementGate / MCPRequestMapper with a real Policy.
    5. Assert startup succeeds, tools load, authorization decisions are correct.
"""

from __future__ import annotations

import asyncio
import json
import sys
import tempfile
import unittest
from pathlib import Path
from typing import Any
from unittest.mock import AsyncMock, MagicMock, patch

import mcp.types as mcp_types
from dmint import TrustedContext
from dmint.errors import AuthorizationError
from dmint.models import Decision, NO_RESOURCE
from dmint.policy import Policy, PolicyError

from dmint.mcp import (
    DiscoveryMode,
    DisclosureMode,
    EnforcementGate,
    MCPConfigurationError,
    MCPIntegrationConfig,
    MCPMappedRequest,
    MCPMappingError,
    MCPRequestMapper,
    MCPToolBinding,
    MCPTransportType,
)
from dmint.mcp.proxy import DmintMCPProxy

from dmint.cli.create_mcp_policy import (
    _assert_no_secrets_in_dict,
    run_create_mcp_policy_wizard,
    validate_mcp_protection_config,
)
from dmint.cli.io_utils import atomic_write_json


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_tool_binding(tool_name: str, integration_id: str) -> MCPToolBinding:
    """Build the MCPToolBinding exactly as validate_mcp_protection_config does."""
    capability = f"mcp.{integration_id}.{tool_name}"
    return MCPToolBinding(
        tool_name=tool_name,
        capability=capability,
        discovery=DiscoveryMode.EXPOSED,
    )


def _build_protection_config(
    policy_file: str,
    integrations: list[dict[str, Any]],
) -> dict[str, Any]:
    """Build an mcp_protection.json dict in the exact format dmint-cli generates."""
    return {
        "policy_file": policy_file,
        "integrations": integrations,
    }


def _integ_dict(
    integration_id: str,
    command: str,
    args: list[str] | None = None,
    transport: str = "stdio",
    tool_names: list[str] | None = None,
) -> dict[str, Any]:
    """Build an integration entry in the format MCPIntegration.to_dict() produces."""
    bindings: dict[str, Any] = {}
    for name in tool_names or []:
        bindings[name] = {
            "tool_name": name,
            "capability": f"mcp.{integration_id}.{name}",
            "discovery": "exposed",
        }
    return {
        "integration_id": integration_id,
        "transport": transport,
        "connection": {"command": command, "args": args or []},
        "tool_bindings": bindings,
    }


def _cfg_from_integ_dict(integ: dict[str, Any]) -> MCPIntegrationConfig:
    """Parse one integration dict entry into a real MCPIntegrationConfig.

    This is the exact same logic that the production runtime loader would use;
    it calls MCPIntegrationConfig directly — no fake parser.
    """
    integration_id = integ["integration_id"]
    transport_str = integ.get("transport", "stdio")
    conn = integ.get("connection", {})
    raw_bindings = integ.get("tool_bindings", {})

    tool_bindings: list[MCPToolBinding] = []
    if isinstance(raw_bindings, dict):
        for tool_name, spec in raw_bindings.items():
            if isinstance(spec, dict):
                tool_bindings.append(
                    MCPToolBinding(
                        tool_name=spec.get("tool_name", tool_name),
                        capability=spec.get("capability", f"mcp.{integration_id}.{tool_name}"),
                        discovery=spec.get("discovery", "exposed"),
                    )
                )
    elif isinstance(raw_bindings, list):
        for spec in raw_bindings:
            if isinstance(spec, dict) and "tool_name" in spec and "capability" in spec:
                tool_bindings.append(
                    MCPToolBinding(
                        tool_name=spec["tool_name"],
                        capability=spec["capability"],
                        discovery=spec.get("discovery", "exposed"),
                    )
                )

    return MCPIntegrationConfig(
        integration_id=integration_id,
        command=conn.get("command", ""),
        args=conn.get("args", []),
        transport_type=transport_str,
        tool_bindings=tool_bindings,
        default_discovery=DiscoveryMode.HIDDEN,
    )


def _policy_for_tools(
    integration_id: str,
    tool_names: list[str],
    effect: str = "allow",
) -> Policy:
    """Build a runtime-compatible policy for the given integration tools.

    The mapper splits capability 'mcp.<integ>.<tool>' as tool='mcp',
    action='<integ>.<tool>', so policy rules must use that exact form.
    """
    rules = []
    for tool_name in tool_names:
        rules.append(
            {
                "effect": effect,
                "tool": "mcp",
                "action": f"{integration_id}.{tool_name}",
                "resource": "*",
            }
        )
    return Policy.from_mapping({"rules": rules})


def _make_downstream_client(tool_names: list[str]) -> MagicMock:
    """Build a mock DownstreamMCPClient that returns the given tool names."""
    client = MagicMock()
    client.__class__.__name__ = "DownstreamMCPClient"

    # list_tools returns real mcp.types.Tool objects
    tools = [
        mcp_types.Tool(
            name=name,
            description=f"tool {name}",
            inputSchema={"type": "object", "properties": {}},
        )
        for name in tool_names
    ]
    client.list_tools = AsyncMock(return_value=tools)

    def _call_tool_side_effect(name, arguments=None):
        return mcp_types.CallToolResult(content=[mcp_types.TextContent(type="text", text=f"result:{name}")])

    client.call_tool = AsyncMock(side_effect=_call_tool_side_effect)

    # Make isinstance(client, DownstreamMCPClient) pass
    from dmint.mcp.client import DownstreamMCPClient

    client.__class__ = DownstreamMCPClient
    return client


# ---------------------------------------------------------------------------
# 1. Config parsing: generated → validated → MCPIntegrationConfig
# ---------------------------------------------------------------------------


class ProtectionConfigParsingTests(unittest.TestCase):
    """Req 4 & 8: Feed generated artifact into the actual dmint-mcp runtime parser."""

    def test_single_integration_parses_to_real_mcpintegrationconfig(self):
        """The generated config round-trips through the real MCPIntegrationConfig constructor."""
        integ = _integ_dict(
            "postgres", "npx", ["-y", "@modelcontextprotocol/server-postgres"], tool_names=["query", "schema"]
        )
        cfg = _cfg_from_integ_dict(integ)
        self.assertIsInstance(cfg, MCPIntegrationConfig)
        self.assertEqual(cfg.integration_id, "postgres")
        self.assertEqual(cfg.transport_type, MCPTransportType.STDIO)
        self.assertEqual(cfg.command, "npx")
        self.assertEqual(cfg.args, ("-y", "@modelcontextprotocol/server-postgres"))

    def test_tool_bindings_load_with_canonical_capability_form(self):
        """Each tool binding carries the mcp.<integration>.<tool> canonical capability."""
        integ = _integ_dict("postgres", "npx", tool_names=["query", "schema"])
        cfg = _cfg_from_integ_dict(integ)
        self.assertIn("query", cfg.tool_bindings)
        self.assertIn("schema", cfg.tool_bindings)
        self.assertEqual(cfg.tool_bindings["query"].capability, "mcp.postgres.query")
        self.assertEqual(cfg.tool_bindings["schema"].capability, "mcp.postgres.schema")

    def test_zero_tools_parses_safely(self):
        """Req 11: An integration with no tool bindings must load without error."""
        integ = _integ_dict("empty-server", "npx", tool_names=[])
        cfg = _cfg_from_integ_dict(integ)
        self.assertIsInstance(cfg, MCPIntegrationConfig)
        self.assertEqual(len(cfg.tool_bindings), 0)

    def test_multiple_integrations_each_parse_independently(self):
        """Req 10: Multiple integrations are each independently parsed."""
        integ_a = _integ_dict("alpha", "cmd-a", tool_names=["read"])
        integ_b = _integ_dict("beta", "cmd-b", tool_names=["write"])
        cfg_a = _cfg_from_integ_dict(integ_a)
        cfg_b = _cfg_from_integ_dict(integ_b)
        self.assertEqual(cfg_a.integration_id, "alpha")
        self.assertEqual(cfg_b.integration_id, "beta")
        self.assertIn("read", cfg_a.tool_bindings)
        self.assertIn("write", cfg_b.tool_bindings)
        self.assertNotIn("write", cfg_a.tool_bindings)
        self.assertNotIn("read", cfg_b.tool_bindings)

    def test_unknown_transport_raises_mcpconfigurationerror(self):
        """Req 12: Unknown transport type raises MCPConfigurationError from the real parser."""
        integ = _integ_dict("bad", "npx", transport="grpc", tool_names=["foo"])
        with self.assertRaises(MCPConfigurationError):
            _cfg_from_integ_dict(integ)

    def test_malformed_config_missing_integration_id_fails(self):
        """Req 13: Malformed config with empty integration_id raises from real parser."""
        integ = _integ_dict("", "npx", tool_names=["foo"])
        with self.assertRaises(MCPConfigurationError):
            _cfg_from_integ_dict(integ)

    def test_malformed_config_missing_command_fails(self):
        """Req 13: Malformed config with empty command raises from real parser."""
        integ = {
            "integration_id": "ok",
            "transport": "stdio",
            "connection": {"command": "", "args": []},
            "tool_bindings": {},
        }
        with self.assertRaises(MCPConfigurationError):
            _cfg_from_integ_dict(integ)

    def test_duplicate_integration_ids_detected_by_validator(self):
        """Req 14: validate_mcp_protection_config detects and rejects duplicate integration IDs."""
        from dmint.cli.errors import CLIError

        config = _build_protection_config(
            "policy.json",
            [
                _integ_dict("postgres", "npx", tool_names=["query"]),
                _integ_dict("postgres", "node", tool_names=["read"]),  # duplicate ID
            ],
        )
        with self.assertRaises(CLIError) as ctx:
            validate_mcp_protection_config(config)
        self.assertIn("Duplicate integration ID", str(ctx.exception))


# ---------------------------------------------------------------------------
# 2. validate_mcp_protection_config: uses real dmint_mcp parser
# ---------------------------------------------------------------------------


class ValidateMCPProtectionConfigTests(unittest.TestCase):
    """Req 4: validate_mcp_protection_config must call the real MCPIntegrationConfig."""

    def test_valid_single_integration_passes(self):
        config = _build_protection_config(
            "policy.json",
            [_integ_dict("postgres", "npx", ["-y", "pg-mcp"], tool_names=["query"])],
        )
        # Must not raise
        validate_mcp_protection_config(config)

    def test_valid_multi_integration_passes(self):
        config = _build_protection_config(
            "policy.json",
            [
                _integ_dict("alpha", "cmd-a", tool_names=["read"]),
                _integ_dict("beta", "cmd-b", tool_names=["write"]),
            ],
        )
        validate_mcp_protection_config(config)

    def test_missing_policy_file_fails(self):
        config = {"integrations": [_integ_dict("pg", "npx", tool_names=["q"])]}
        from dmint.cli.errors import CLIError

        with self.assertRaises(CLIError):
            validate_mcp_protection_config(config)

    def test_empty_integrations_list_fails(self):
        config = {"policy_file": "policy.json", "integrations": []}
        from dmint.cli.errors import CLIError

        with self.assertRaises(CLIError):
            validate_mcp_protection_config(config)

    def test_unknown_transport_fails_via_real_parser(self):
        from dmint.cli.errors import CLIError

        config = _build_protection_config(
            "policy.json",
            [_integ_dict("x", "cmd", transport="grpc", tool_names=["t"])],
        )
        with self.assertRaises(CLIError):
            validate_mcp_protection_config(config)

    def test_no_secrets_in_config(self):
        """Req 7: validate_mcp_protection_config asserts no secrets in config dict."""
        config = _build_protection_config(
            "policy.json",
            [_integ_dict("postgres", "npx", tool_names=["query"])],
        )
        config["integrations"][0]["access_token"] = "tok_supersecret"
        from dmint.cli.errors import CLIError

        with self.assertRaises(CLIError) as ctx:
            _assert_no_secrets_in_dict(config)
        self.assertIn("secret", str(ctx.exception).lower())

    def test_config_round_trip_json_to_real_parser(self):
        """Req 8: Generated → serialized → loaded → real MCPIntegrationConfig."""
        original_config = _build_protection_config(
            "policy.json",
            [_integ_dict("pg", "npx", ["-y", "pg-mcp"], tool_names=["query", "schema"])],
        )
        # Serialize (as atomic_write_json does) and deserialize
        serialized = json.dumps(original_config, sort_keys=True, indent=2)
        loaded = json.loads(serialized)

        # Feed to real validate_mcp_protection_config — must not raise
        validate_mcp_protection_config(loaded)

        # Construct real MCPIntegrationConfig from each loaded integration
        for integ_dict in loaded["integrations"]:
            cfg = _cfg_from_integ_dict(integ_dict)
            self.assertIsInstance(cfg, MCPIntegrationConfig)


# ---------------------------------------------------------------------------
# 3. MCPRequestMapper: capability translation matches runtime behavior
# ---------------------------------------------------------------------------


class CapabilityTranslationCompatibilityTests(unittest.TestCase):
    """Req 6: Verify capability → ToolRequest translation through the real mapper."""

    def _make_mapper(self, integration_id: str, tool_names: list[str]) -> MCPRequestMapper:
        cfg = MCPIntegrationConfig(
            integration_id=integration_id,
            command="npx",
            args=[],
            tool_bindings=[_make_tool_binding(t, integration_id) for t in tool_names],
        )
        return MCPRequestMapper(cfg, agent_id="test-agent", context=TrustedContext({}))

    def test_canonical_capability_produces_correct_tool_and_action(self):
        """mcp.<integ>.<tool> binding → tool='mcp', action='<integ>.<tool>' in ToolRequest."""
        mapper = self._make_mapper("postgres", ["query"])
        mapped = mapper.map(tool_name="query", arguments={})
        self.assertEqual(mapped.tool_request.tool, "mcp")
        self.assertEqual(mapped.tool_request.action, "postgres.query")
        self.assertEqual(mapped.capability, "mcp.postgres.query")

    def test_multiple_tools_each_translate_correctly(self):
        """Each tool in an integration maps to a distinct tool+action pair."""
        mapper = self._make_mapper("postgres", ["query", "schema", "delete"])
        for tool_name in ["query", "schema", "delete"]:
            mapped = mapper.map(tool_name=tool_name, arguments={})
            self.assertEqual(mapped.tool_request.tool, "mcp")
            self.assertEqual(mapped.tool_request.action, f"postgres.{tool_name}")

    def test_unbound_tool_raises_mcpmappingerror(self):
        """Req 6 fail-closed: a tool not in bindings raises MCPMappingError."""
        mapper = self._make_mapper("postgres", ["query"])
        with self.assertRaises(MCPMappingError):
            mapper.map(tool_name="unknown_tool", arguments={})

    def test_policy_must_use_mcp_form_to_authorize(self):
        """Policy rule must match tool='mcp', action='<integ>.<tool>' to authorize."""
        mapper = self._make_mapper("postgres", ["query"])
        mapped = mapper.map(tool_name="query", arguments={})

        # Wrong form — tool name as integration_id, action as tool_name
        policy_wrong = Policy.from_mapping(
            {"rules": [{"effect": "allow", "tool": "postgres", "action": "query", "resource": "*"}]}
        )
        self.assertEqual(policy_wrong.evaluate(mapped.tool_request), Decision.DENY)

        # Correct runtime-compatible form
        policy_correct = Policy.from_mapping(
            {"rules": [{"effect": "allow", "tool": "mcp", "action": "postgres.query", "resource": "*"}]}
        )
        self.assertEqual(policy_correct.evaluate(mapped.tool_request), Decision.ALLOW)

    def test_two_integrations_do_not_collide_in_policy(self):
        """Same tool name on two different integrations maps to distinct action values."""
        mapper_a = self._make_mapper("alpha", ["read"])
        mapper_b = self._make_mapper("beta", ["read"])
        mapped_a = mapper_a.map(tool_name="read", arguments={})
        mapped_b = mapper_b.map(tool_name="read", arguments={})
        # Both have tool='mcp' but distinct actions
        self.assertEqual(mapped_a.tool_request.tool, "mcp")
        self.assertEqual(mapped_a.tool_request.action, "alpha.read")
        self.assertEqual(mapped_b.tool_request.tool, "mcp")
        self.assertEqual(mapped_b.tool_request.action, "beta.read")
        # A policy allowing alpha.read must NOT authorize beta.read
        policy = Policy.from_mapping(
            {"rules": [{"effect": "allow", "tool": "mcp", "action": "alpha.read", "resource": "*"}]}
        )
        self.assertEqual(policy.evaluate(mapped_a.tool_request), Decision.ALLOW)
        self.assertEqual(policy.evaluate(mapped_b.tool_request), Decision.DENY)


# ---------------------------------------------------------------------------
# 4. EnforcementGate: real runtime enforcement
# ---------------------------------------------------------------------------


class EnforcementGateRuntimeTests(unittest.IsolatedAsyncioTestCase):
    """Req 5 & 6: Start a real EnforcementGate and exercise authorization decisions."""

    def _make_gate(
        self,
        integration_id: str,
        tool_names: list[str],
        effect: str = "allow",
    ) -> tuple[EnforcementGate, MagicMock]:
        cfg = MCPIntegrationConfig(
            integration_id=integration_id,
            command="npx",
            args=[],
            tool_bindings=[_make_tool_binding(t, integration_id) for t in tool_names],
            default_discovery=DiscoveryMode.EXPOSED,
        )
        policy = _policy_for_tools(integration_id, tool_names, effect=effect)
        client = _make_downstream_client(tool_names)
        gate = EnforcementGate(client, cfg, policy=policy, agent_id="test-agent")
        return gate, client

    async def test_startup_succeeds_single_integration(self):
        """Req 6a: Startup (EnforcementGate construction) succeeds for one integration."""
        gate, _ = self._make_gate("postgres", ["query"])
        self.assertIsNotNone(gate)
        self.assertIsInstance(gate, EnforcementGate)

    async def test_integrations_load_with_real_config(self):
        """Req 6b: Integration config and tool bindings are loaded into the gate."""
        gate, _ = self._make_gate("postgres", ["query", "schema"])
        self.assertIsNotNone(gate.mapper)
        self.assertIn("query", gate.mapper._config.tool_bindings)
        self.assertIn("schema", gate.mapper._config.tool_bindings)

    async def test_tool_bindings_load(self):
        """Req 6c: Tool bindings are available from the gate's config."""
        gate, _ = self._make_gate("postgres", ["query"])
        binding = gate.mapper._config.tool_bindings["query"]
        self.assertEqual(binding.tool_name, "query")
        self.assertEqual(binding.capability, "mcp.postgres.query")

    async def test_list_tools_matches_config_discovery(self):
        """Req 6d: list_tools returns tools matching the binding discovery config."""
        gate, client = self._make_gate("postgres", ["query", "schema"])
        # Mock downstream list_tools to return the bound tools
        result = await gate.list_tools()
        # All tools are EXPOSED by default in _make_tool_binding
        tool_names = {t.name for t in result.tools}
        self.assertIn("query", tool_names)
        self.assertIn("schema", tool_names)

    async def test_authorized_tool_call_succeeds(self):
        """Req 6e: Authorized tool call (ALLOW policy) succeeds and calls downstream."""
        gate, client = self._make_gate("postgres", ["query"])
        result = await gate.route_call(
            integration_id="postgres",
            tool_name="query",
            arguments={"sql": "SELECT 1"},
        )
        self.assertIsInstance(result, mcp_types.CallToolResult)
        self.assertFalse(result.is_error)
        client.call_tool.assert_called_once()

    async def test_unauthorized_tool_call_is_denied(self):
        """Req 6f: Denied tool call (DENY policy) raises AuthorizationError before downstream."""
        gate, client = self._make_gate("postgres", ["query"], effect="deny")
        with self.assertRaises(AuthorizationError) as ctx:
            await gate.route_call(
                integration_id="postgres",
                tool_name="query",
                arguments={},
            )
        self.assertIn("denied", str(ctx.exception).lower())
        # Downstream must NOT have been called
        client.call_tool.assert_not_called()

    async def test_unknown_tool_denied_before_downstream(self):
        """Fail-closed: unknown tool → MCPMappingError before downstream execution."""
        gate, client = self._make_gate("postgres", ["query"])
        with self.assertRaises(MCPMappingError):
            await gate.route_call(
                integration_id="postgres",
                tool_name="nonexistent_tool",
                arguments={},
            )
        client.call_tool.assert_not_called()

    async def test_empty_policy_denies_all_tools(self):
        """Req 3 (default deny): empty policy denies all tool calls."""
        cfg = MCPIntegrationConfig(
            integration_id="postgres",
            command="npx",
            args=[],
            tool_bindings=[_make_tool_binding("query", "postgres")],
        )
        policy = Policy.from_mapping({"rules": []})  # empty policy → deny-all
        client = _make_downstream_client(["query"])
        gate = EnforcementGate(client, cfg, policy=policy, agent_id="test-agent")
        with self.assertRaises(AuthorizationError):
            await gate.route_call(
                integration_id="postgres",
                tool_name="query",
                arguments={},
            )
        client.call_tool.assert_not_called()


# ---------------------------------------------------------------------------
# 5. Multiple integrations runtime
# ---------------------------------------------------------------------------


class MultipleIntegrationsRuntimeTests(unittest.IsolatedAsyncioTestCase):
    """Req 10: Test multiple integrations each with their own gate and policy."""

    async def test_two_integrations_with_separate_gates(self):
        """Each integration has its own gate; policies are isolated."""

        def _gate(iid, tools, effect="allow"):
            cfg = MCPIntegrationConfig(
                integration_id=iid,
                command="npx",
                args=[],
                tool_bindings=[_make_tool_binding(t, iid) for t in tools],
            )
            policy = _policy_for_tools(iid, tools, effect=effect)
            client = _make_downstream_client(tools)
            return EnforcementGate(client, cfg, policy=policy, agent_id="test-agent"), client

        gate_alpha, client_alpha = _gate("alpha", ["read"])
        gate_beta, client_beta = _gate("beta", ["write"])

        result_alpha = await gate_alpha.route_call(integration_id="alpha", tool_name="read", arguments={})
        self.assertFalse(result_alpha.is_error)
        client_alpha.call_tool.assert_called_once()

        result_beta = await gate_beta.route_call(integration_id="beta", tool_name="write", arguments={})
        self.assertFalse(result_beta.is_error)
        client_beta.call_tool.assert_called_once()

    async def test_alpha_policy_cannot_authorize_beta_tool(self):
        """Policy for integration alpha must not authorize beta's tools (no cross-contamination)."""
        cfg_beta = MCPIntegrationConfig(
            integration_id="beta",
            command="npx",
            args=[],
            tool_bindings=[_make_tool_binding("write", "beta")],
        )
        # Use alpha's policy on beta's gate
        alpha_policy = _policy_for_tools("alpha", ["write"])  # tool='mcp', action='alpha.write'
        client_beta = _make_downstream_client(["write"])
        gate_beta = EnforcementGate(client_beta, cfg_beta, policy=alpha_policy, agent_id="test-agent")
        # beta's mapper will produce action='beta.write', alpha's policy covers action='alpha.write'
        with self.assertRaises(AuthorizationError):
            await gate_beta.route_call(integration_id="beta", tool_name="write", arguments={})
        client_beta.call_tool.assert_not_called()

    async def test_same_tool_name_on_two_servers_is_isolated(self):
        """Req 9 (single) & Req 10 (multiple): Same tool name on two servers → distinct capabilities."""
        cfg_a = MCPIntegrationConfig(
            integration_id="serverA",
            command="npx",
            args=[],
            tool_bindings=[_make_tool_binding("read", "serverA")],
        )
        cfg_b = MCPIntegrationConfig(
            integration_id="serverB",
            command="npx",
            args=[],
            tool_bindings=[_make_tool_binding("read", "serverB")],
        )
        # Each server gets a policy that only allows its own read tool
        policy_a = _policy_for_tools("serverA", ["read"])
        policy_b = _policy_for_tools("serverB", ["read"])

        client_a = _make_downstream_client(["read"])
        client_b = _make_downstream_client(["read"])

        gate_a = EnforcementGate(client_a, cfg_a, policy=policy_a, agent_id="agent")
        gate_b = EnforcementGate(client_b, cfg_b, policy=policy_b, agent_id="agent")

        result_a = await gate_a.route_call(integration_id="serverA", tool_name="read", arguments={})
        self.assertFalse(result_a.is_error)

        result_b = await gate_b.route_call(integration_id="serverB", tool_name="read", arguments={})
        self.assertFalse(result_b.is_error)

        # Cross-contamination: serverA's policy must NOT authorize serverB's tool
        gate_cross = EnforcementGate(client_b, cfg_b, policy=policy_a, agent_id="agent")
        with self.assertRaises(AuthorizationError):
            await gate_cross.route_call(integration_id="serverB", tool_name="read", arguments={})


# ---------------------------------------------------------------------------
# 6. Zero-tools safety
# ---------------------------------------------------------------------------


class ZeroToolsSafetyTests(unittest.IsolatedAsyncioTestCase):
    """Req 11: An integration with zero tools must start safely and deny all calls."""

    async def test_zero_tools_gate_starts_safely(self):
        """MCPIntegrationConfig and EnforcementGate with no bindings must construct cleanly."""
        cfg = MCPIntegrationConfig(
            integration_id="empty-server",
            command="npx",
            args=[],
            tool_bindings=[],
        )
        policy = Policy.from_mapping({"rules": []})
        client = _make_downstream_client([])
        gate = EnforcementGate(client, cfg, policy=policy, agent_id="test-agent")
        self.assertIsNotNone(gate)

    async def test_zero_tools_list_tools_returns_empty(self):
        """list_tools on a zero-tool integration returns an empty list."""
        cfg = MCPIntegrationConfig(
            integration_id="empty-server",
            command="npx",
            args=[],
            tool_bindings=[],
            default_discovery=DiscoveryMode.EXPOSED,
        )
        policy = Policy.from_mapping({"rules": []})
        client = _make_downstream_client([])
        gate = EnforcementGate(client, cfg, policy=policy, agent_id="test-agent")
        result = await gate.list_tools()
        self.assertEqual(result.tools, [])

    async def test_zero_tools_any_call_raises_mapping_error(self):
        """Calling any tool on a zero-binding config fails with MCPMappingError."""
        cfg = MCPIntegrationConfig(
            integration_id="empty-server",
            command="npx",
            args=[],
            tool_bindings=[],
        )
        policy = Policy.from_mapping({"rules": []})
        client = _make_downstream_client([])
        gate = EnforcementGate(client, cfg, policy=policy, agent_id="test-agent")
        with self.assertRaises(MCPMappingError):
            await gate.route_call(
                integration_id="empty-server",
                tool_name="anything",
                arguments={},
            )
        client.call_tool.assert_not_called()


# ---------------------------------------------------------------------------
# 7. Full round-trip: generated artifact → file → loaded → runtime
# ---------------------------------------------------------------------------


class FullRoundTripTests(unittest.IsolatedAsyncioTestCase):
    """Req 8: generated → serialized → loaded → runtime-valid."""

    async def test_single_integration_artifact_round_trip(self):
        """Req 9: One integration's config serializes, reloads, and passes runtime validation."""
        original_config = _build_protection_config(
            "policy.json",
            [_integ_dict("postgres", "npx", ["-y", "pg-mcp"], tool_names=["query", "schema"])],
        )
        with tempfile.TemporaryDirectory() as d:
            config_path = Path(d) / "mcp_protection.json"
            atomic_write_json(config_path, original_config)

            # Load from disk
            loaded = json.loads(config_path.read_text())

        # Validate with the real validator (uses real MCPIntegrationConfig internally)
        validate_mcp_protection_config(loaded)

        # Construct real MCPIntegrationConfig from each loaded entry
        for integ_dict_entry in loaded["integrations"]:
            cfg = _cfg_from_integ_dict(integ_dict_entry)
            self.assertIsInstance(cfg, MCPIntegrationConfig)
            self.assertEqual(cfg.integration_id, "postgres")

    async def test_multi_integration_artifact_round_trip(self):
        """Req 10: Multiple integrations round-trip through disk and real parser."""
        original_config = _build_protection_config(
            "policy.json",
            [
                _integ_dict("alpha", "cmd-a", tool_names=["read"]),
                _integ_dict("beta", "cmd-b", tool_names=["write"]),
            ],
        )
        with tempfile.TemporaryDirectory() as d:
            config_path = Path(d) / "mcp_protection.json"
            atomic_write_json(config_path, original_config)
            loaded = json.loads(config_path.read_text())

        validate_mcp_protection_config(loaded)
        cfgs = [_cfg_from_integ_dict(e) for e in loaded["integrations"]]
        self.assertEqual({c.integration_id for c in cfgs}, {"alpha", "beta"})

    async def test_round_trip_gates_enforce_correctly_after_reload(self):
        """After round-trip through disk, enforcement decisions are correct."""
        original_config = _build_protection_config(
            "policy.json",
            [_integ_dict("pg", "npx", tool_names=["query"])],
        )
        with tempfile.TemporaryDirectory() as d:
            config_path = Path(d) / "mcp_protection.json"
            atomic_write_json(config_path, original_config)
            loaded = json.loads(config_path.read_text())

        integ_dict_entry = loaded["integrations"][0]
        cfg = _cfg_from_integ_dict(integ_dict_entry)

        allow_policy = _policy_for_tools("pg", ["query"], effect="allow")
        deny_policy = _policy_for_tools("pg", ["query"], effect="deny")
        client = _make_downstream_client(["query"])

        gate_allow = EnforcementGate(client, cfg, policy=allow_policy, agent_id="agent")
        result = await gate_allow.route_call(integration_id="pg", tool_name="query", arguments={})
        self.assertFalse(result.is_error)

        gate_deny = EnforcementGate(client, cfg, policy=deny_policy, agent_id="agent")
        with self.assertRaises(AuthorizationError):
            await gate_deny.route_call(integration_id="pg", tool_name="query", arguments={})

    @patch("dmint.cli.create_mcp_policy.discover_mcp_tools_generic", new_callable=AsyncMock)
    @patch("dmint.cli.create_mcp_policy.OpenAICompatClient")
    async def test_wizard_generated_artifacts_load_and_run_in_real_runtime(self, mock_client_cls, mock_discover):
        """Req 3, 4, 5, 6: Generate via dmint-cli wizard, parse via real dmint-mcp, run real gate."""
        mock_discover.return_value = [
            {
                "name": "query",
                "description": "Execute read-only SQL queries",
                "input_schema": {"type": "object", "properties": {"sql": {"type": "string"}}},
                "integration_id": "postgres",
                "capability": "mcp.postgres.query",
                "annotations": {},
            },
            {
                "name": "delete_all",
                "description": "Drop all database tables",
                "input_schema": {"type": "object", "properties": {}},
                "integration_id": "postgres",
                "capability": "mcp.postgres.delete_all",
                "annotations": {},
            },
        ]

        mock_client = MagicMock()
        mock_client.model = "gpt-4o-mini"
        mock_client.base_url = "https://api.openai.com/v1"
        mock_client.chat_completion.return_value = json.dumps(
            {
                "type": "policy_ready",
                "rules": [
                    {
                        "effect": "allow",
                        "tool": "mcp",
                        "action": "postgres.query",
                        "resource": "*",
                    },
                    {
                        "effect": "deny",
                        "tool": "mcp",
                        "action": "postgres.delete_all",
                        "resource": "*",
                    },
                ],
            }
        )
        mock_client_cls.return_value = mock_client

        with tempfile.TemporaryDirectory() as d:
            temp_path = Path(d)
            md_path = temp_path / "access.md"
            md_path.write_text("Allow query tool, deny delete_all tool.", encoding="utf-8")
            policy_json_path = temp_path / "policy.json"
            protection_json_path = temp_path / "mcp_protection.json"

            # 3. Generate configuration using dmint-cli
            policy, protection_config = await asyncio.to_thread(
                run_create_mcp_policy_wizard,
                command="mcp-server-postgres",
                integration_id="postgres",
                access_md_file=md_path,
                output_json_file=policy_json_path,
                config_output_file=protection_json_path,
                api_key="sk-test",
                non_interactive=True,
                auto_confirm=True,
            )

            # Both files must exist
            self.assertTrue(policy_json_path.exists())
            self.assertTrue(protection_json_path.exists())

            # 4. Feed that exact generated artifact into the actual dmint-mcp runtime parser
            loaded_config = json.loads(protection_json_path.read_text(encoding="utf-8"))
            validate_mcp_protection_config(loaded_config)

            # Construct real MCPIntegrationConfig
            integ_dict = loaded_config["integrations"][0]
            real_mcp_config = _cfg_from_integ_dict(integ_dict)
            self.assertIsInstance(real_mcp_config, MCPIntegrationConfig)

            # Load the real Policy from generated policy.json
            loaded_policy_data = json.loads(policy_json_path.read_text(encoding="utf-8"))
            real_policy = Policy.from_mapping(loaded_policy_data)

            # 5. Start a real test runtime (EnforcementGate)
            downstream_client = _make_downstream_client(["query", "delete_all"])
            gate = EnforcementGate(
                downstream_client,
                real_mcp_config,
                policy=real_policy,
                agent_id="test-agent",
            )

            # 6. Verify:
            # - startup succeeds
            self.assertIsNotNone(gate)
            # - integrations load
            self.assertEqual(gate.mapper.integration_id, "postgres")
            # - tool bindings load
            self.assertIn("query", real_mcp_config.tool_bindings)
            self.assertIn("delete_all", real_mcp_config.tool_bindings)
            # - discovery behavior matches config
            tools_result = await gate.list_tools()
            tool_names = {t.name for t in tools_result.tools}
            self.assertEqual(tool_names, {"query", "delete_all"})
            # - authorized tool call succeeds
            auth_call = await gate.route_call(
                integration_id="postgres",
                tool_name="query",
                arguments={"sql": "SELECT 1"},
            )
            self.assertFalse(auth_call.is_error)
            downstream_client.call_tool.assert_called_once()

            # - unauthorized tool call is denied
            downstream_client.call_tool.reset_mock()
            with self.assertRaises(AuthorizationError):
                await gate.route_call(
                    integration_id="postgres",
                    tool_name="delete_all",
                    arguments={},
                )
            downstream_client.call_tool.assert_not_called()


# ---------------------------------------------------------------------------
# 8. No secrets in configuration
# ---------------------------------------------------------------------------


class NoSecretsInConfigTests(unittest.TestCase):
    """Req 7: Ensure configuration contains no secrets."""

    def test_clean_generated_config_has_no_secrets(self):
        config = _build_protection_config(
            "policy.json",
            [_integ_dict("postgres", "npx", ["-y", "pg-mcp"], tool_names=["query"])],
        )
        # Must not raise
        _assert_no_secrets_in_dict(config)

    def test_bearer_token_in_config_detected(self):
        from dmint.cli.errors import CLIError

        config = _build_protection_config("p.json", [])
        config["bearer_token"] = "tok_abc"
        with self.assertRaises(CLIError):
            _assert_no_secrets_in_dict(config)

    def test_api_key_in_integration_env_detected(self):
        from dmint.cli.errors import CLIError

        config = _build_protection_config(
            "policy.json",
            [_integ_dict("pg", "npx", tool_names=["q"])],
        )
        config["integrations"][0]["api_key"] = "sk-verysecret"
        with self.assertRaises(CLIError):
            _assert_no_secrets_in_dict(config)

    def test_atomic_write_json_file_contains_no_secrets(self):
        """A written config file must be cleanly verifiable after disk load."""
        config = _build_protection_config(
            "policy.json",
            [_integ_dict("postgres", "npx", ["-y", "pg-mcp"], tool_names=["query"])],
        )
        with tempfile.TemporaryDirectory() as d:
            path = Path(d) / "mcp_protection.json"
            atomic_write_json(path, config)
            on_disk = json.loads(path.read_text())
        # Must not raise
        _assert_no_secrets_in_dict(on_disk)


# ---------------------------------------------------------------------------
# 9. Real downstream subprocess runtime test
# ---------------------------------------------------------------------------


class RealSubprocessRuntimeTests(unittest.IsolatedAsyncioTestCase):
    """Req 5 & 6: Start a real test runtime connecting to an actual downstream MCP process."""

    async def test_real_downstream_mcp_subprocess_enforcement(self):
        mock_server_script = str(Path(__file__).resolve().parent.parent / "mcp" / "mock_server.py")

        # 1. Build integration configuration
        integ_dict = _integ_dict(
            "mock-server",
            sys.executable,
            args=[mock_server_script],
            tool_names=["echo", "delete_database"],
        )
        config = _build_protection_config("policy.json", [integ_dict])
        validate_mcp_protection_config(config)

        # 2. Parse into real MCPIntegrationConfig
        mcp_cfg = _cfg_from_integ_dict(integ_dict)

        # 3. Build real Policy allowing only 'echo'
        policy = Policy.from_mapping(
            {
                "rules": [
                    {
                        "effect": "allow",
                        "tool": "mcp",
                        "action": "mock-server.echo",
                        "resource": "*",
                    },
                ]
            }
        )

        # 4. Start real DmintMCPProxy connected to real downstream subprocess
        proxy = DmintMCPProxy(mcp_cfg, policy=policy)
        try:
            await proxy.connect()

            # Startup succeeds and gate is ready
            self.assertIsNotNone(proxy.gate)

            # Discovery matches config
            tools_result = await proxy.list_tools()
            tool_names = {t.name for t in tools_result.tools}
            self.assertIn("echo", tool_names)
            self.assertIn("delete_database", tool_names)

            # Authorized tool call succeeds against the real downstream server
            auth_result = await proxy.gate.route_call(
                integration_id="mock-server",
                tool_name="echo",
                arguments={"message": "hello from dmint-cli test"},
            )
            self.assertFalse(auth_result.is_error)
            self.assertEqual(auth_result.content[0].text, "echo: hello from dmint-cli test")

            # Unauthorized tool call is denied by Dmint policy before downstream execution
            with self.assertRaises(AuthorizationError):
                await proxy.gate.route_call(
                    integration_id="mock-server",
                    tool_name="delete_database",
                    arguments={"target": "prod-db"},
                )
        finally:
            await proxy.disconnect()


if __name__ == "__main__":
    unittest.main()
