"""Phase 8 / Step 13 Integration Test — dmint-cli & dmint-mcp canonical compatibility.

Verifies end-to-end compatibility between dmint-cli generated artifacts (mcp_protection.json)
and the dmint-mcp Step 2 Configuration Loader & Multi-Server Gateway runtime.
"""

from __future__ import annotations

import asyncio
from datetime import datetime, timezone
import json
from pathlib import Path
import sys
import tempfile
import unittest


from dmint.cli.create_mcp_policy import validate_mcp_protection_config
from dmint.cli.mcp_connections import MCPIntegration, MCPTransport
import mcp.types as types

from dmint.models import Decision
from dmint.policy import Policy, policy_digest
from dmint.mcp import (
    DiscoveryMode,
    DisclosureMode,
    DownstreamMCPClient,
    MCPGateway,
    MCPGatewayConfig,
    MCPIntegrationConfig,
    load_protection_config,
)


class MockDownstreamClient(DownstreamMCPClient):
    """Mock downstream client simulating an MCP server."""

    def __init__(self, config: MCPIntegrationConfig, tools: list[types.Tool] | None = None) -> None:
        super().__init__(config)
        self._connected = False
        self._tools = tools or []
        self.call_log: list[tuple[str, dict]] = []

    @property
    def is_connected(self) -> bool:
        return self._connected

    async def connect(self) -> None:
        self._connected = True

    async def disconnect(self) -> None:
        self._connected = False

    async def list_tools(self) -> list[types.Tool]:
        return list(self._tools)

    async def call_tool(self, name: str, arguments: dict | None = None) -> types.CallToolResult:
        self.call_log.append((name, arguments or {}))
        return types.CallToolResult(
            content=[types.TextContent(type="text", text=f"executed {self.config.integration_id}:{name}")]
        )


class TestMCPCLICompatibility(unittest.IsolatedAsyncioTestCase):
    """Integration tests verifying compatibility between dmint-cli artifacts and dmint-mcp gateway."""

    async def asyncSetUp(self) -> None:
        self.tmpdir = tempfile.TemporaryDirectory()
        self.tmppath = Path(self.tmpdir.name)

        # 1. Use real CLI MCPIntegration models
        self.integ1 = MCPIntegration(
            integration_id="github",
            transport=MCPTransport.STDIO,
            connection={
                "command": "mcp-server-github",
                "args": ["--repo", "dmint/repo"],
                "env": {"LANG": "C.UTF-8"},
                "timeout": 25.0,
            },
            discovered_tools=[
                {
                    "name": "get_issue",
                    "description": "Get issue details",
                    "inputSchema": {"type": "object", "properties": {"id": {"type": "integer"}}},
                },
                {
                    "name": "close_issue",
                    "description": "Close an issue",
                    "inputSchema": {"type": "object", "properties": {"id": {"type": "integer"}}},
                },
            ],
        )

        self.integ2 = MCPIntegration(
            integration_id="postgres",
            transport=MCPTransport.STDIO,
            connection={
                "command": "mcp-server-postgres",
                "args": ["postgresql://localhost/db"],
                "timeout": 35.0,
            },
            discovered_tools=[
                {
                    "name": "query",
                    "description": "Run read-only queries",
                    "inputSchema": {"type": "object", "properties": {"sql": {"type": "string"}}},
                },
                {
                    "name": "execute",
                    "description": "Execute database statements",
                    "inputSchema": {"type": "object", "properties": {"sql": {"type": "string"}}},
                },
            ],
        )

        # 2. Build policy matching the canonical capabilities
        # Canonical capabilities generated by CLI: mcp.<integration_id>.<tool_name>
        # Tool = "mcp", Action = "<integration_id>.<tool_name>"
        self.policy_data = {
            "rules": [
                {"tool": "mcp", "action": "github.get_issue", "effect": "allow"},
                {"tool": "mcp", "action": "github.close_issue", "effect": "approval_required"},
                {"tool": "mcp", "action": "postgres.query", "effect": "allow"},
                {"tool": "mcp", "action": "postgres.execute", "effect": "approval_required"},
            ]
        }
        self.policy_path = self.tmppath / "policy.json"
        self.policy_path.write_text(json.dumps(self.policy_data), encoding="utf-8")

        # 3. Generate canonical CLI mcp_protection.json dict
        self.protection_dict = {
            "policy_file": "policy.json",
            "integrations": [
                self.integ1.to_dict(),
                self.integ2.to_dict(),
            ],
        }

        # 4. Validate with real CLI validator
        validate_mcp_protection_config(self.protection_dict)

        # 5. Write to disk
        self.protection_path = self.tmppath / "mcp_protection.json"
        self.protection_path.write_text(json.dumps(self.protection_dict), encoding="utf-8")

    async def asyncTearDown(self) -> None:
        self.tmpdir.cleanup()

    async def test_cli_protection_config_loads_and_runs_gateway(self) -> None:
        """mcp_protection.json generated by dmint-cli must load cleanly and execute in MCPGateway."""
        # Step 1: Load config using real dmint_mcp config loader
        config = load_protection_config(self.protection_path)
        self.assertIsInstance(config, MCPGatewayConfig)
        self.assertEqual(len(config.integrations), 2)

        # Verify github integration
        gh_cfg = config.get_integration("github")
        self.assertIsNotNone(gh_cfg)
        self.assertEqual(gh_cfg.command, "mcp-server-github")
        self.assertEqual(gh_cfg.args, ("--repo", "dmint/repo"))
        self.assertEqual(gh_cfg.call_timeout, 25.0)
        self.assertIn("get_issue", gh_cfg.tool_bindings)
        self.assertEqual(gh_cfg.tool_bindings["get_issue"].capability, "mcp.github.get_issue")
        self.assertEqual(gh_cfg.tool_bindings["get_issue"].discovery, DiscoveryMode.EXPOSED)

        # Verify postgres integration
        pg_cfg = config.get_integration("postgres")
        self.assertIsNotNone(pg_cfg)
        self.assertEqual(pg_cfg.command, "mcp-server-postgres")
        self.assertEqual(pg_cfg.call_timeout, 35.0)
        self.assertIn("query", pg_cfg.tool_bindings)
        self.assertEqual(pg_cfg.tool_bindings["query"].capability, "mcp.postgres.query")

        # Step 2: Instantiate real MCPGateway with mock downstream clients
        clients: dict[str, MockDownstreamClient] = {}

        def client_factory(cfg: MCPIntegrationConfig) -> DownstreamMCPClient:
            client = MockDownstreamClient(
                cfg,
                tools=[
                    types.Tool(name=b.tool_name, description=f"{cfg.integration_id} {b.tool_name}", input_schema={})
                    for b in cfg.tool_bindings.values()
                ],
            )
            clients[cfg.integration_id] = client
            return client

        gateway = MCPGateway(config, client_factory=client_factory)

        # Step 3: Connect and list tools
        await gateway.connect()
        try:
            res = await gateway.list_tools()
            tool_names = [t.name for t in res.tools]

            # In this setup:
            # github has: get_issue, close_issue
            # postgres has: query, execute
            # None collide, so all can be listed by bare name or namespaced
            self.assertIn("get_issue", tool_names)
            self.assertIn("close_issue", tool_names)
            self.assertIn("query", tool_names)
            self.assertIn("execute", tool_names)

            # Step 4: Route allowed call via namespaced name
            gh_res = await gateway.route_call("github.get_issue", {"id": 42})
            self.assertFalse(gh_res.is_error)
            self.assertEqual(clients["github"].call_log[-1], ("get_issue", {"id": 42}))

            # Step 5: Route allowed call via bare name
            pg_res = await gateway.route_call("query", {"sql": "SELECT 1"})
            self.assertFalse(pg_res.is_error)
            self.assertEqual(clients["postgres"].call_log[-1], ("query", {"sql": "SELECT 1"}))

            # Step 6: Verify denied / unknown tool
            from dmint.mcp.errors import MCPError

            with self.assertRaises(MCPError):
                await gateway.route_call("unknown_tool", {})

        finally:
            await gateway.disconnect()


if __name__ == "__main__":
    unittest.main()
